import React, { useEffect, useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Feather, Flame, Sparkles, AlertCircle, Compass, Heart } from 'lucide-react';
import { Shayari, MoodCategory } from './types';
import { MOODS, SEED_SHAYARIS } from './data/shayariData';
import MoodSelector from './components/MoodSelector';
import ShayariCard from './components/ShayariCard';
import DailyFeatured from './components/DailyFeatured';
import AiGenerator from './components/AiGenerator';
import SearchAndFilters from './components/SearchAndFilters';

export default function App() {
  // Shared States
  const [shayaris, setShayaris] = useState<Shayari[]>(SEED_SHAYARIS);
  const [activeCategory, setActiveCategory] = useState<MoodCategory>('love');
  const [searchQuery, setSearchQuery] = useState('');
  const [showFavoritesOnly, setShowFavoritesOnly] = useState(false);
  const [showAiOnly, setShowAiOnly] = useState(false);
  
  // Local Persistence States
  const [favorites, setFavorites] = useState<string[]>([]);

  // Load favorites and custom-generated shayaris from localStorage on mount
  useEffect(() => {
    // 1. Favorites
    const storedFavs = localStorage.getItem('shayari_favorites');
    if (storedFavs) {
      try {
        setFavorites(JSON.parse(storedFavs));
      } catch (e) {
        console.error('Failed to parse favorites:', e);
      }
    }

    // 2. Custom persistent AI-generated shayaris
    const storedCustom = localStorage.getItem('shayari_custom_generated');
    if (storedCustom) {
      try {
        const parsedCustom: Shayari[] = JSON.parse(storedCustom);
        // Prepend custom generated ones so they show up at the top
        setShayaris((prev) => [...parsedCustom, ...prev]);
      } catch (e) {
        console.error('Failed to parse custom generated shayaris:', e);
      }
    }

    // 3. Fetch up-to-date base seed from the server to guarantee consistency
    async function fetchServerSeeds() {
      try {
        const res = await fetch('/api/shayaris');
        if (res.ok) {
          const result = await res.json();
          if (result.success && Array.isArray(result.data)) {
            // Merge newly fetched server seeds with any existing user custom generated ones
            setShayaris((currentList) => {
              const customOnly = currentList.filter((s) => s.id.startsWith('ai-') || s.id.startsWith('fallback-'));
              return [...customOnly, ...result.data];
            });
          }
        }
      } catch (err) {
        console.log('Using preloaded seeds due to offline status:', err);
      }
    }
    fetchServerSeeds();
  }, []);

  // Sync favorites back to localStorage
  const handleToggleFavorite = (id: string) => {
    setFavorites((prev) => {
      const updated = prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id];
      localStorage.setItem('shayari_favorites', JSON.stringify(updated));
      return updated;
    });
  };

  // Callback: When a brand new Shayari is generated by Gemini on the fly
  const handleNewShayariGenerated = (newShayari: Shayari) => {
    // Save to state
    setShayaris((prev) => [newShayari, ...prev]);
    
    // Auto shift view to the mood category they generated to find it
    setActiveCategory(newShayari.category);

    // Persist in localStorage so custom creations remain
    try {
      const storedCustom = localStorage.getItem('shayari_custom_generated');
      const currentCustomList: Shayari[] = storedCustom ? JSON.parse(storedCustom) : [];
      const updatedCustomList = [newShayari, ...currentCustomList];
      localStorage.setItem('shayari_custom_generated', JSON.stringify(updatedCustomList));
    } catch (e) {
      console.error('Failed to persist generated shayari:', e);
    }
  };

  // Find the color schemes of our active category for smooth theme animations
  const currentMoodConfig = useMemo(() => {
    return MOODS.find((m) => m.category === activeCategory) || MOODS[0];
  }, [activeCategory]);

  // Combined Search & Mood Filter logic
  const filteredShayaris = useMemo(() => {
    return shayaris.filter((shayari) => {
      // 1. Mood Filter
      if (activeCategory && shayari.category !== activeCategory) {
        return false;
      }

      // 2. Favorites Filter
      if (showFavoritesOnly && !favorites.includes(shayari.id)) {
        return false;
      }

      // 3. AI Only Filter
      if (showAiOnly && !shayari.isAiGenerated) {
        return false;
      }

      // 4. Search Query Filter (Matches Hindi, Roman Translit, Translation, Author, Meaning)
      if (searchQuery.trim() !== '') {
        const query = searchQuery.toLowerCase().trim();
        return (
          shayari.hindi.toLowerCase().includes(query) ||
          shayari.englishTranslit.toLowerCase().includes(query) ||
          shayari.translation.toLowerCase().includes(query) ||
          shayari.meaning.toLowerCase().includes(query) ||
          shayari.author.toLowerCase().includes(query)
        );
      }

      return true;
    });
  }, [shayaris, activeCategory, showFavoritesOnly, showAiOnly, searchQuery, favorites]);

  return (
    <div className="relative min-h-screen text-slate-200 flex flex-col transition-colors duration-1000">
      {/* Dynamic shifting background ambient elements */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        {/* Shifting dynamic gradient backdrop */}
        <div
          className={`absolute inset-0 bg-gradient-to-b ${currentMoodConfig.gradient} transition-all duration-1000 opacity-95`}
        />
        
        {/* Elegant Dark theme radial gradient proxy and glowing circles */}
        <div className="absolute inset-0 opacity-25 pointer-events-none bg-[radial-gradient(circle_at_50%_50%,_rgba(99,102,241,0.15)_0%,_transparent_60%)]" />
        <div className="absolute top-[-5%] right-[-5%] w-[45vw] h-[45vw] bg-indigo-500/10 blur-[120px] rounded-full pointer-events-none ambient-bg-glow" />
        <div className="absolute bottom-[-5%] left-[-5%] w-[50vw] h-[50vw] bg-purple-500/10 blur-[120px] rounded-full pointer-events-none ambient-bg-glow" />
      </div>

      {/* Main Content Area */}
      <div className="relative z-10 flex-1 flex flex-col">
        {/* Header Section from Elegant Dark mockup */}
        <header className="relative z-10 flex flex-col md:flex-row items-center justify-between px-6 md:px-10 py-8 w-full max-w-6xl mx-auto border-b border-white/5 gap-4">
          <div className="flex items-center space-x-3">
            {/* <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <span className="text-white font-serif font-bold text-xl">A</span>
            </div> */}
            <div>
              <h1 className="text-2xl font-light tracking-tight text-white">
                Aapki<span className="font-bold text-indigo-400">Shayari</span>
              </h1>
              <p className="text-[10px] font-mono tracking-widest text-slate-500 uppercase">
                Premium Hindi Poetry Web
              </p>
            </div>
          </div>

          {/* <div className="flex items-center space-x-4">
            <div className="flex items-center gap-2.5 text-xs font-semibold text-slate-400 bg-white/[0.03] border border-white/10 px-4 py-2 rounded-full shadow-xl">
              <span className="relative flex h-2.5 w-2.5">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-indigo-500"></span>
              </span>
              <span className="text-xs text-indigo-300 font-mono tracking-wider uppercase">Gemini AI Engine Active</span>
            </div>
          </div> */}
        </header>

        {/* Featured Section: Shayari of the Day */}
        <section className="pt-4 pb-2">
          <DailyFeatured favorites={favorites} onToggleFavorite={handleToggleFavorite} />
        </section>

        {/* AI Generator Panel */}
        {/* <section className="py-2">
          <AiGenerator
            activeCategory={activeCategory}
            onNewShayariGenerated={handleNewShayariGenerated}
            favorites={favorites}
            onToggleFavorite={handleToggleFavorite}
          />
        </section> */}

        {/* Mood Selector (Dynamic ambient changing cards) */}
        <section className="py-2">
          <MoodSelector activeCategory={activeCategory} onSelectCategory={(cat) => setActiveCategory(cat as MoodCategory)} />
        </section>

        {/* Search and filter controls */}
        <section className="py-2">
          <SearchAndFilters
            searchQuery={searchQuery}
            onSearchChange={setSearchQuery}
            showFavoritesOnly={showFavoritesOnly}
            onToggleFavoritesOnly={() => setShowFavoritesOnly(!showFavoritesOnly)}
            showAiOnly={showAiOnly}
            onToggleAiOnly={() => setShowAiOnly(!showAiOnly)}
            totalCount={filteredShayaris.length}
          />
        </section>

        {/* Main list Grid of filtered Shayaris */}
        <main className="w-full max-w-6xl mx-auto px-4 py-6 flex-1">
          <AnimatePresence mode="popLayout">
            {filteredShayaris.length > 0 ? (
              <motion.div
                layout
                className="grid grid-cols-1 md:grid-cols-2 gap-6"
                id="shayari-list-grid"
              >
                {filteredShayaris.map((shayari) => (
                  <ShayariCard
                    key={shayari.id}
                    shayari={shayari}
                    isFavorite={favorites.includes(shayari.id)}
                    onToggleFavorite={handleToggleFavorite}
                  />
                ))}
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="flex flex-col items-center justify-center text-center p-12 py-20 rounded-[32px] bg-white/[0.02] border border-white/10 backdrop-blur-md max-w-lg mx-auto"
                id="empty-list-placeholder"
              >
                <div className="w-12 h-12 rounded-full bg-white/5 border border-white/10 flex items-center justify-center text-indigo-400 mb-4">
                  <Compass className="w-6 h-6" />
                </div>
                <h4 className="font-serif text-lg text-white">कोई शायरी नहीं मिली</h4>
                <p className="text-xs text-slate-400 font-sans mt-2 leading-relaxed">
                  {showFavoritesOnly 
                    ? "You haven't bookmarked any verses in this mood yet. Mark your favorite verses by clicking the heart button."
                    : "No matching verses found for this search. Try searching for a different keyword, or ask our AI to compose a fresh one!"}
                </p>
                {showFavoritesOnly && (
                  <button
                    onClick={() => setShowFavoritesOnly(false)}
                    className="mt-5 text-xs font-bold uppercase tracking-widest px-5 py-2.5 bg-indigo-600 text-white rounded-full hover:bg-indigo-500 transition-colors shadow-lg shadow-indigo-600/20 cursor-pointer"
                  >
                    View All Verses
                  </button>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </main>

        {/* Application Footer */}
        <footer className="w-full max-w-6xl mx-auto px-6 py-12 mt-12 border-t border-white/5 text-center flex flex-col md:flex-row items-center justify-between text-xs text-slate-500 gap-4">
          <div className="flex items-center gap-2">
            <Feather size={14} className="text-indigo-400/60" />
            <span>© 2026 Shayri Poetry Portal. All rights reserved.</span>
          </div>
          <div className="flex items-center gap-4">
            <span className="font-mono hover:text-white transition-colors duration-200 cursor-help">
              Built by Prince
            </span>
            <span>•</span>
            <span className="hover:text-white transition-colors duration-200 cursor-help">
              Designed for Urdu & Hindi Lovers
            </span>
          </div>
        </footer>
      </div>
    </div>
  );
}
